_format_version: "2.1"
_transform: true

services:
  - name: auth-v1-open
    url: http://gotrue:9999/
    plugins:
      - name: cors
  - name: auth-v1-open-callback
    url: http://gotrue:9999/callback
    plugins:
      - name: cors
  - name: auth-v1-open-authorize
    url: http://gotrue:9999/authorize
    plugins:
      - name: cors

  - name: rest-v1
    url: http://postgrest:3000/
    plugins:
      - name: cors
      - name: key-auth
        config:
          hide_credentials: false
      - name: acl
        config:
          hide_groups_header: true

  - name: storage-v1
    url: http://minio:9000/
    plugins:
      - name: cors

consumers:
  - username: anon
    keyauth_credentials:
      - key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
    acls:
      - group: anon

  - username: service_role
    keyauth_credentials:
      - key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
    acls:
      - group: admin

routes:
  - name: auth-v1-open
    service: auth-v1-open
    strip_path: true
    paths:
      - /auth/v1/settings
      - /auth/v1/signup
      - /auth/v1/signin
      - /auth/v1/verify
      - /auth/v1/recover
      - /auth/v1/resend
      - /auth/v1/logout
      - /auth/v1/token
      - /auth/v1/user
      - /auth/v1/otp
      - /auth/v1/magiclink
      - /auth/v1/invite
      - /auth/v1/admin

  - name: auth-v1-open-callback
    service: auth-v1-open-callback
    strip_path: true
    paths:
      - /auth/v1/callback

  - name: auth-v1-open-authorize
    service: auth-v1-open-authorize
    strip_path: true
    paths:
      - /auth/v1/authorize

  - name: rest-v1
    service: rest-v1
    strip_path: true
    paths:
      - /rest/v1/

  - name: storage-v1
    service: storage-v1
    strip_path: false
    paths:
      - /storage/v1/object/

plugins:
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - HEAD
        - PUT
        - PATCH
        - POST
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - X-Auth-Token
        - Authorization
        - X-Forwarded-For
        - X-Forwarded-Proto
        - X-Forwarded-Port
      exposed_headers:
        - X-Auth-Token
      credentials: true
      max_age: 3600